version: '3'
services:
  proxy:
    image: nginx:alpine
    networks:
      - rock
      - country
      - folk
    ports:
      - 8000:80
    volumes:
    # overwrite default nginx config
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # example of using include
      - $PWD/nginx-include.conf:/nginx-include-mounted-in-container.conf:ro
  country:
    networks:
      - country
    build:
      context: .
      args:
        JAR_FILE: countries-assembly-1.0.1.jar
  rock:
    networks:
      - rock
    build:
      context: .
      args:
        JAR_FILE: airports-assembly-1.0.1.jar
  folk:
    networks:
      - folk
    build:
      context: .
      args:
        JAR_FILE: airports-assembly-1.1.0.jar

networks:
  folk: {}
  rock: {}
  country: {}
